# Generated by Django 5.2.8 on 2026-01-19 02:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('seniorsergeant', 'Senior Sergeant'), ('warrant_officer', 'Warrant Officer II'), ('warrant_officer', 'Warrant Officer I'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant colonel', 'Lieutenant Colonel'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('class', 'Class Session'), ('exam', 'Exam Session'), ('bedcheck', 'Bedcheck Session'), ('lab', 'Lab Session'), ('other', 'Other')], default='class', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_refresh_interval', models.IntegerField(default=300, help_text='Minutes after start time to still mark as present', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('qr_code_secret', models.CharField(blank=True, max_length=255)),
                ('qr_last_generated', models.DateTimeField(blank=True, null=True)),
                ('qr_generation_count', models.IntegerField(default=0)),
                ('enable_qr_scan', models.BooleanField(default=True)),
                ('enable_manual_marking', models.BooleanField(default=True)),
                ('enable_biometric', models.BooleanField(default=False)),
                ('require_location', models.BooleanField(default=False)),
                ('allowed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_radius_meters', models.IntegerField(blank=True, default=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_late_minutes', models.IntegerField(default=10, help_text='Minutes after start time to still mark as present', validators=[django.core.validators.MinValueValidator(0)])),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.subject')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_created', 'Session Created'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_cancelled', 'Session Cancelled'), ('qr_generated', 'QR Code Generated'), ('attendance_marked', 'Attendance Marked'), ('attendance_updated', 'Attendance Updated'), ('attendance_deleted', 'Attendance Deleted'), ('bulk_import', 'Bulk Import'), ('biometric_sync', 'Biometric Sync')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.attendancesession')),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Session Logs',
                'db_table': 'attendance_session_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_notices_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.subject')),
            ],
            options={
                'db_table': 'class_notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassNoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('class_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.classnotice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_notice_read_statuses',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('cat', 'CAT'), ('final', 'Final'), ('project', 'Project')], default='cat', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_duration', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.subject')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exams/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'])])),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.exam')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reports', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_reports_created', to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(related_name='exam_reports', to='core.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reports', to='core.subject')),
            ],
            options={
                'db_table': 'exam_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.exam')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_graded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
        migrations.CreateModel(
            name='ExamResultNotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_statuses', to='core.examresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_notification_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_result_notification_read_statuses',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice_read_statuses',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10)),
                ('marking_method', models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual Entry'), ('biometric', 'Biometric'), ('admin', 'Admin Override')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked_in_session', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='core.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'db_table': 'session_attendances',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco Device'), ('fingerprint', 'Fingerprint Scanner'), ('other', 'Other')], default='zkteco', max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('biometric_id', models.CharField(help_text='Student ID in biometric device', max_length=100)),
                ('scan_time', models.DateTimeField()),
                ('verification_type', models.CharField(blank=True, max_length=50)),
                ('verification_score', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from device', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to='core.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to=settings.AUTH_USER_MODEL)),
                ('session_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_records', to='core.sessionattendance')),
            ],
            options={
                'verbose_name': 'Biometric Record',
                'verbose_name_plural': 'Biometric Records',
                'db_table': 'biometric_records',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.class')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.subject')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-class_obj', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'class_obj', 'subject', 'date'), name='unique_attendance_per_student_class_subject_date')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_id'], name='attendance__session_14ed26_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_obj', 'scheduled_start'], name='attendance__class_o_b6cb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='attendance__status_498ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['session', 'timestamp'], name='attendance__session_11fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['action', 'timestamp'], name='attendance__action_c2f12b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classnoticereadstatus',
            unique_together={('user', 'class_notice')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'exam_date')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='examresultnotificationreadstatus',
            index=models.Index(fields=['user', 'exam_result'], name='exam_result_user_id_6d60ea_idx'),
        ),
        migrations.AddIndex(
            model_name='examresultnotificationreadstatus',
            index=models.Index(fields=['read_at'], name='exam_result_read_at_1e64c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresultnotificationreadstatus',
            unique_together={('user', 'exam_result')},
        ),
        migrations.AlterUniqueTogether(
            name='noticereadstatus',
            unique_together={('user', 'notice')},
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'status'], name='session_att_session_73faca_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student', 'marked_at'], name='session_att_student_e77ab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['device_id', 'scan_time'], name='biometric_r_device__432c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['student', 'scan_time'], name='biometric_r_student_35dbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['processed', 'scan_time'], name='biometric_r_process_44827c_idx'),
        ),
    ]
