# Generated by Django 5.2.8 on 2026-05-19 05:43

import core.managers
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. NOC', max_length=200)),
                ('device_type', models.CharField(default='zkteco_f22', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=4370)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('location_description', models.CharField(blank=True, help_text='Physical location of the device', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_sync_records', models.IntegerField(default=0)),
                ('total_synced_records', models.IntegerField(default=0)),
                ('sync_interval_seconds', models.IntegerField(default=30, help_text='HOw often to poll this device (seconds)')),
                ('time_offset_seconds', models.IntegerField(default=0, help_text='Offset to apply if the device clock differs from server')),
                ('connection_timeout', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biometric_devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('completion', 'Course Completion'), ('achievement', 'Achievement'), ('participation', 'Participation'), ('excellence', 'Excellence Award')], default='completion', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('header_text', models.CharField(default='Certificate of Completion', help_text='Main title on the certificate', max_length=500)),
                ('body_template', models.TextField(blank=True, help_text='Custom body text template. Placeholders: {student_name}, {course_name}, {class_name}, {completion_date}, {grade}')),
                ('footer_text', models.CharField(blank=True, help_text='Footer text (e.g. accreditation information)', max_length=500)),
                ('use_school_branding', models.BooleanField(default=True, help_text='Use school logo and colours instead of custom ones')),
                ('custom_logo', models.ImageField(blank=True, help_text='Override school logo for this template', null=True, upload_to='certificate_logos/')),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('accent_color', models.CharField(blank=True, max_length=7)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures/')),
                ('signatory_name', models.CharField(blank=True, max_length=200)),
                ('signatory_title', models.CharField(blank=True, max_length=200)),
                ('secondary_signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures/')),
                ('secondary_signatory_name', models.CharField(blank=True, max_length=200)),
                ('secondary_signatory_title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default template for this school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_templates',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique school code (e.g., 'KACEME')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='School code must be uppercase letters, numbers and underscores only', regex='^[A-Z0-9_]+$')])),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#1976D2', max_length=7)),
                ('secondary_color', models.CharField(default='#424242', max_length=7)),
                ('accent_color', models.CharField(default='#FFC107', max_length=7)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('max_students', models.IntegerField(default=5000)),
                ('max_instructors', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'school_admins',
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('commandant', 'Commandant'), ('chief instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_memberships',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10)),
                ('marking_method', models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual Entry'), ('biometric', 'Biometric'), ('admin', 'Admin Override')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session_attendances',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(help_text="Zero-padded sequential number, e.g. '001'", max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Index must be numeric digits only')])),
                ('assigned_to', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_indexes',
                'ordering': ['class_obj', 'index_number'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'two_factor_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['course', 'name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_obj', 'name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.TenantAwareUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='index_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for student indexes', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='index_start_from',
            field=models.PositiveIntegerField(default=1, help_text='First index number assigned to new students (e.g. 50 → first student gets 050).'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_via',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('certificate', 'Certificate Issued'), ('admin_closure', 'Admin Class Closure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students'), ('instructor', 'Instructors'), ('admin', 'Admins'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor')], default='all', help_text='Target audience for this notice.', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('senior_sergeant', 'Senior Sergeant'), ('warrant_officer_ii', 'Warrant Officer II'), ('warrant_officer_i', 'Warrant Officer I'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], help_text='Base role. Overridden by active membership role when affiliated.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='svc_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_obj')},
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('class', 'Class Session'), ('exam', 'Exam Session'), ('bedcheck', 'Bedcheck Session'), ('lab', 'Lab Session'), ('other', 'Other')], default='class', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_refresh_interval', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('qr_code_secret', models.CharField(blank=True, max_length=255)),
                ('qr_last_generated', models.DateTimeField(blank=True, null=True)),
                ('qr_generation_count', models.IntegerField(default=0)),
                ('enable_qr_scan', models.BooleanField(default=True)),
                ('enable_manual_marking', models.BooleanField(default=True)),
                ('enable_biometric', models.BooleanField(default=False)),
                ('require_location', models.BooleanField(default=False)),
                ('allowed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_radius_meters', models.IntegerField(blank=True, default=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_late_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.school')),
            ],
            options={
                'db_table': 'attendance_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(default='', editable=False, help_text='Unique code for public certificate verification', max_length=32, unique=True)),
                ('student_name', models.CharField(default='', max_length=300)),
                ('student_svc_number', models.CharField(blank=True, default='', max_length=50)),
                ('student_rank', models.CharField(blank=True, default='', max_length=100)),
                ('course_name', models.CharField(default='', max_length=200)),
                ('class_name', models.CharField(default='', max_length=200)),
                ('final_grade', models.CharField(blank=True, max_length=10)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, help_text='Date the student completed the course', null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('revocation_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/generated/')),
                ('file_generated_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.class')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.enrollment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_revoked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='core.certificatetemplate')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.school')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_notices_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.school')),
            ],
            options={
                'db_table': 'class_notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.department'),
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('hod', 'Head of Department'), ('member', 'Member')], default='member', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department_memberships',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('cat', 'CAT'), ('final', 'Final'), ('project', 'Project')], default='cat', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_duration', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.school')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reports', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_reports_created', to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(blank=True, related_name='reports', to='core.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_reports', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_reports', to='core.school')),
            ],
            options={
                'db_table': 'exam_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Set to True when the Instructor submits resultsPrevents further edits until an HOD approves a ResultEditRequest.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.exam')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_graded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.school')),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
        migrations.CreateModel(
            name='ResultEditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Instructor must explain why the result needs to be changed.')),
                ('proposed_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proposed_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='HOD feedback on the decision.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='core.examresult')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_edit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_edit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_edit_requests', to='core.school')),
            ],
            options={
                'db_table': 'result_edit_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.school')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='PersonalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exam_result', 'Exam Result'), ('exam_report_remark', 'Exam Report Remark'), ('general', 'General'), ('alert', 'Alert')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('exam_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to='core.examresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to='core.school')),
            ],
            options={
                'db_table': 'personal_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OICRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remark_type', models.CharField(choices=[('class', 'Overall Class Performance'), ('subject', 'Subject Performance')], default='class', max_length=50)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.class')),
                ('oic', models.ForeignKey(limit_choices_to={'role': 'oic'}, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='If null, this is an overall class remark.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.school')),
            ],
            options={
                'db_table': 'oic_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OICAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin or commandant who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oic_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(help_text='The class this OIC is assigned to oversee.', on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.class')),
                ('oic', models.ForeignKey(help_text='The Officer in Charge assigned to oversee this class.', limit_choices_to={'role': 'oic'}, on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.school')),
            ],
            options={
                'db_table': 'oic_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to='core.school')),
            ],
            options={
                'db_table': 'notice_read_statuses',
            },
        ),
        migrations.CreateModel(
            name='ExamResultNotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_statuses', to='core.examresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_notification_read_statuses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_notification_read_statuses', to='core.school')),
            ],
            options={
                'db_table': 'exam_result_notification_read_statuses',
            },
        ),
        migrations.CreateModel(
            name='ExamReportRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('instructor', 'Instructor'), ('oic', 'Officer in Charge')], max_length=20)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_report_remarks', to=settings.AUTH_USER_MODEL)),
                ('exam_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.examreport')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_report_remarks', to='core.school')),
            ],
            options={
                'db_table': 'exam_report_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exams/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'])])),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.exam')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attachments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attachments', to='core.school')),
            ],
            options={
                'db_table': 'exam_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.school'),
        ),
        migrations.CreateModel(
            name='ClassNoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('class_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.classnotice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notice_read_statuses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notice_read_statuses', to='core.school')),
            ],
            options={
                'db_table': 'class_notice_read_statuses',
            },
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='core.school'),
        ),
        migrations.CreateModel(
            name='CertificateDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('pdf', 'PDF Download'), ('html', 'HTML Preview'), ('view', 'View Only')], default='pdf', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='core.certificate')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_downloads', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_downloads', to='core.school')),
            ],
            options={
                'db_table': 'certificate_download_logs',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(help_text='The user_id stored on the ZKTeco device', max_length=100)),
                ('device_user_name', models.CharField(blank=True, help_text='Name stored on the device (for reference)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='core.biometricdevice')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_mappings', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_user_mappings', to='core.school')),
            ],
            options={
                'db_table': 'biometric_user_mappings',
            },
        ),
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco Device'), ('fingerprint', 'Fingerprint Scanner'), ('other', 'Other')], default='zkteco', max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('biometric_id', models.CharField(max_length=100)),
                ('scan_time', models.DateTimeField()),
                ('verification_type', models.CharField(blank=True, max_length=50)),
                ('verification_score', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to='core.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to='core.school')),
            ],
            options={
                'db_table': 'biometric_records',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='core.school'),
        ),
        migrations.CreateModel(
            name='AttendanceSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_created', 'Session Created'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_cancelled', 'Session Cancelled'), ('qr_generated', 'QR Code Generated'), ('attendance_marked', 'Attendance Marked'), ('attendance_updated', 'Attendance Updated'), ('attendance_deleted', 'Attendance Deleted'), ('bulk_import', 'Bulk Import'), ('biometric_sync', 'Biometric Sync')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.attendancesession')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_session_logs', to='core.school')),
            ],
            options={
                'db_table': 'attendance_session_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.class')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.subject')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.school')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', 'student__last_name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.school'),
        ),
        migrations.AddField(
            model_name='notice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='classes_school__da98b2_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['instructor', 'is_active'], name='classes_instruc_116563_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['class_obj', 'is_active'], name='subjects_class_o_75cf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='subjects_school__b445cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['instructor', 'is_active'], name='subjects_instruc_e3e34f_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('class_code__isnull', False)), fields=('course', 'class_code'), name='unique_class_code_per_course'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_admins', to='core.school'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_transfers', to='core.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.schoolmembership'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_obj', 'is_active'], name='enrollments_class_o_c72672_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='enrollments_student_8f846d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'is_active'], name='enrollments_school__acef63_idx'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked_in_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='core.school'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='core.attendancesession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='session_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_records', to='core.sessionattendance'),
        ),
        migrations.AddField(
            model_name='studentindex',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_indexes', to='core.class'),
        ),
        migrations.AddField(
            model_name='studentindex',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_indexes', to='core.enrollment'),
        ),
        migrations.AddField(
            model_name='studentindex',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_indexes', to='core.school'),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['user', 'role', 'is_active'], name='department__user_id_d228b1_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['department', 'role', 'is_active'], name='department__departm_c355f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'hod')), fields=('department',), name='unique_active_hod_per_department'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department', 'user'), name='unique_active_user_per_department'),
        ),
        migrations.AddIndex(
            model_name='resulteditrequest',
            index=models.Index(fields=['exam_result', 'status'], name='result_edit_exam_re_cf99e0_idx'),
        ),
        migrations.AddIndex(
            model_name='resulteditrequest',
            index=models.Index(fields=['requested_by', 'status'], name='result_edit_request_3341f0_idx'),
        ),
        migrations.AddIndex(
            model_name='resulteditrequest',
            index=models.Index(fields=['school', 'status'], name='result_edit_school__94264c_idx'),
        ),
        migrations.AddConstraint(
            model_name='resulteditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('exam_result',), name='unique_pending_edit_request_per_result'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_user_id_29277a_idx'),
        ),
        migrations.AddIndex(
            model_name='personalnotification',
            index=models.Index(fields=['user', 'is_read'], name='personal_no_user_id_42d731_idx'),
        ),
        migrations.AddIndex(
            model_name='personalnotification',
            index=models.Index(fields=['user', 'created_at'], name='personal_no_user_id_6e3daf_idx'),
        ),
        migrations.AddIndex(
            model_name='personalnotification',
            index=models.Index(fields=['notification_type'], name='personal_no_notific_9a4b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='oicremark',
            index=models.Index(fields=['oic', 'class_obj'], name='oic_remarks_oic_id_7280c6_idx'),
        ),
        migrations.AddIndex(
            model_name='oicremark',
            index=models.Index(fields=['class_obj', 'remark_type'], name='oic_remarks_class_o_3e7d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='oicremark',
            index=models.Index(fields=['school', 'created_at'], name='oic_remarks_school__0fed7c_idx'),
        ),
        migrations.AddIndex(
            model_name='oicassignment',
            index=models.Index(fields=['oic', 'is_active'], name='oic_assignm_oic_id_0a86fa_idx'),
        ),
        migrations.AddIndex(
            model_name='oicassignment',
            index=models.Index(fields=['class_obj', 'is_active'], name='oic_assignm_class_o_c7d10b_idx'),
        ),
        migrations.AddIndex(
            model_name='oicassignment',
            index=models.Index(fields=['school', 'is_active'], name='oic_assignm_school__b47ffb_idx'),
        ),
        migrations.AddConstraint(
            model_name='oicassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('oic', 'class_obj'), name='unique_active_oic_per_class'),
        ),
        migrations.AlterUniqueTogether(
            name='noticereadstatus',
            unique_together={('user', 'notice')},
        ),
        migrations.AddIndex(
            model_name='examresultnotificationreadstatus',
            index=models.Index(fields=['user', 'exam_result'], name='exam_result_user_id_6d60ea_idx'),
        ),
        migrations.AddIndex(
            model_name='examresultnotificationreadstatus',
            index=models.Index(fields=['read_at'], name='exam_result_read_at_1e64c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresultnotificationreadstatus',
            unique_together={('user', 'exam_result')},
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['school', 'is_submitted'], name='exam_result_school__f2161e_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'is_submitted', 'marks_obtained'], name='exam_result_student_85c263_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'is_submitted', 'student'], name='exam_result_exam_id_4d62f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'is_active'], name='exams_subject_18ac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'is_active'], name='exams_school__17e265_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'exam_date', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classnoticereadstatus',
            unique_together={('user', 'class_notice')},
        ),
        migrations.AlterUniqueTogether(
            name='certificatetemplate',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_1d3ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='certificate_verific_8df4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', 'status'], name='certificate_student_df5bad_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['school', 'issued_at'], name='certificate_school__8bada0_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('student', 'enrollment'), name='unique_certificate_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='biometricusermapping',
            index=models.Index(fields=['device_user_id', 'device'], name='biometric_u_device__ded9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricusermapping',
            index=models.Index(fields=['student', 'device'], name='biometric_u_student_172315_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together={('device', 'device_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='biometricdevice',
            unique_together={('school', 'ip_address', 'port')},
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['session', 'timestamp'], name='attendance__session_11fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['action', 'timestamp'], name='attendance__action_c2f12b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_id'], name='attendance__session_14ed26_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_obj', 'scheduled_start'], name='attendance__class_o_b6cb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='attendance__status_498ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'class_obj', 'date'], name='attendance_student_091d52_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_obj', 'date', 'status'], name='attendance_class_o_dc9f4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'class_obj', 'subject', 'date'), name='unique_attendance_per_student_class_subject_date'),
        ),
        migrations.AlterUniqueTogether(
            name='schooladmin',
            unique_together={('school', 'user')},
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['user', 'status'], name='school_memb_user_id_483c91_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['school', 'status'], name='school_memb_school__6cf94e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['user', 'school', 'status'], name='school_memb_user_id_ba9268_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'school'), name='unique_active_membership_per_school'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'status'], name='session_att_session_73faca_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student', 'marked_at'], name='session_att_student_e77ab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['device_id', 'scan_time'], name='biometric_r_device__432c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['student', 'scan_time'], name='biometric_r_student_35dbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['processed', 'scan_time'], name='biometric_r_process_44827c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentindex',
            index=models.Index(fields=['class_obj', 'index_number'], name='student_ind_class_o_fc0e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentindex',
            index=models.Index(fields=['enrollment'], name='student_ind_enrollm_eaf676_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentindex',
            unique_together={('class_obj', 'index_number')},
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='two_factor__user_id_8d65a7_idx'),
        ),
    ]
