# Generated by Django 5.2.8 on 2026-04-11 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_biometricdevice_certificatetemplate_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreportremark',
            name='author_role',
            field=models.CharField(choices=[('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('instructor', 'Instructor'), ('oic', 'Officer in Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('commandant', 'Commandant'), ('chief instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], help_text='Base role. Overridden by active membership role when affiliated.', max_length=20),
        ),
        migrations.CreateModel(
            name='OICAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin or commandant who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oic_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(help_text='The class this OIC is assigned to oversee.', on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.class')),
                ('oic', models.ForeignKey(help_text='The Officer in Charge assigned to oversee this class.', limit_choices_to={'role': 'oic'}, on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.school')),
            ],
            options={
                'db_table': 'oic_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['oic', 'is_active'], name='oic_assignm_oic_id_0a86fa_idx'), models.Index(fields=['class_obj', 'is_active'], name='oic_assignm_class_o_c7d10b_idx'), models.Index(fields=['school', 'is_active'], name='oic_assignm_school__b47ffb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('oic', 'class_obj'), name='unique_active_oic_per_class')],
            },
        ),
        migrations.CreateModel(
            name='OICRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remark_type', models.CharField(choices=[('class', 'Overall Class Performance'), ('subject', 'Subject Performance')], default='class', max_length=50)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.class')),
                ('oic', models.ForeignKey(limit_choices_to={'role': 'oic'}, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.school')),
                ('subject', models.ForeignKey(blank=True, help_text='If null, this is an overall class remark.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oic_remarks', to='core.subject')),
            ],
            options={
                'db_table': 'oic_remarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['oic', 'class_obj'], name='oic_remarks_oic_id_7280c6_idx'), models.Index(fields=['class_obj', 'remark_type'], name='oic_remarks_class_o_3e7d1c_idx'), models.Index(fields=['school', 'created_at'], name='oic_remarks_school__0fed7c_idx')],
            },
        ),
    ]
