# Generated by Django 5.2.8 on 2026-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_biometricdevice_certificatetemplate_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreportremark',
            name='author_role',
            field=models.CharField(choices=[('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('instructor', 'Instructor'), ('oic', 'Officer in Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('commandant', 'Commandant'), ('chief instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], help_text='Base role. Overridden by active membership role when affiliated.', max_length=20),
        ),
        # OICAssignment and OICRemark are not (re)created here: 0002 already
        # creates both tables for real, with the same fields/indexes/
        # constraints this migration originally duplicated. Re-running these
        # CreateModels would fail with "relation already exists" on a
        # from-scratch replay.
    ]
