# Generated by Django 5.2.8 on 2025-11-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_course_created_by_course_is_active_course_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="created_by",
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("lance_corporal", "Lance Corporal"),
                    ("corporal", "Corporal"),
                    ("sergeant", "Sergeant"),
                    ("seniorsergeant", "Senior Sergeant"),
                    ("warrant_officer", "Warrant Officer II"),
                    ("warrant_officer", "Warrant Officer I"),
                    ("lieutenant", "Lieutenant"),
                    ("captain", "Captain"),
                    ("major", "Major"),
                    ("lieutenant colonel", "Lieutenant Colonel"),
                    ("general", "General"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
