# Generated by Django 5.2.8 on 2026-05-26 21:05
#
# Every operation this migration originally contained (AssessmentComponent,
# StudentComponentResult, subject.grading_mode/pass_mark, exam.component,
# resulteditrequest.component_result, and their indexes/constraints) is a
# duplicate of what the mainline chain (0010, 0011, 0012, 0013, 0019) already
# applies, including the assessmentcomponent.school/subject foreign keys
# (0010's CreateModel for AssessmentComponent includes them inline). This
# file is kept as a no-op because 0023_merge_20260527_1039 depends on it as
# a graph node.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_biometricdevice_certificatetemplate_department_and_more'),
    ]

    operations = []
