# Generated by Django 5.2.8 on 2026-04-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_examreportremark_author_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['school', 'processed', 'scan_time'], name='biometric_r_school__330cca_idx'),
        ),
    ]
