# Generated by Django 5.2.8 on 2025-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_course_created_by_user_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
