# Generated by Django 5.2.8 on 2026-04-13 06:04
#
# This migration's BiometricRecord field/index additions are explicitly
# reverted two migrations later by 0009 (RemoveIndex x2, RemoveField x3,
# AlterField x2 — all matching this file's operations exactly). Its
# BiometricUserMapping additions are moot too: 0007 deletes that model
# entirely and 0009 recreates it from scratch without these fields. The
# whole migration is a complete round-trip no-op in the final schema
# (confirmed via `makemigrations --check`, clean with or without it).
#
# Kept as a no-op rather than deleted because 0006 depends on this name.
# On an empty database this migration's unique_together on
# ('device', 'device_user_id_hash') was harmless (nothing to violate). On a
# database restored from a real backup, existing BiometricUserMapping rows
# share the same default empty-string hash, so building that unique index
# for real fails with a duplicate-key IntegrityError. Since the constraint
# never survives to the final schema anyway, running it for real was never
# necessary.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_biometricrecord_biometric_r_school__330cca_idx'),
    ]

    operations = []
