# Generated by Django 5.2.8 on 2025-11-25 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_subject_subject_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="capacity",
            field=models.FloatField(
                default=30, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
