# Generated by Django 5.2.8 on 2026-04-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_biometricrecord_biometric_r_school__330cca_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='biometricusermapping',
            name='biometric_u_device__ded9d2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='biometric_id_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted biometric ID from device'),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='biometric_id_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='HMAC-SHA256 hash for deduplication queries', max_length=64),
        ),
        migrations.AddField(
            model_name='biometricrecord',
            name='raw_data_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted raw JSON payload'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='device_user_id_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted device user ID'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='device_user_id_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='HMAC-SHA256 hash for lookup queries', max_length=64),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='device_user_name_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted device user name'),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='biometric_id',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: use biometric_id_encrypted', max_length=100),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='DEPRECATED: use raw_data_encrypted', null=True),
        ),
        migrations.AlterField(
            model_name='biometricusermapping',
            name='device_user_id',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: use device_user_id_encrypted', max_length=100),
        ),
        migrations.AlterField(
            model_name='biometricusermapping',
            name='device_user_name',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: use device_user_name_encrypted', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together={('device', 'device_user_id_hash')},
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['biometric_id_hash', 'scan_time'], name='biometric_r_biometr_54b67d_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricusermapping',
            index=models.Index(fields=['device_user_id_hash', 'device'], name='biometric_u_device__f77f78_idx'),
        ),
    ]
