# Generated by Django 5.2.8 on 2026-04-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_biometric_encryption_fields'),
    ]

    operations = [
    ]
