# Generated by Django 5.2.8 on 2026-04-15 04:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260414_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biometricdevice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biometricdevice',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biometricusermapping',
            name='device',
        ),
        migrations.RemoveField(
            model_name='biometricusermapping',
            name='mapped_by',
        ),
        migrations.RemoveField(
            model_name='biometricusermapping',
            name='school',
        ),
        migrations.RemoveField(
            model_name='biometricusermapping',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student__last_name']},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-scheduled_start']},
        ),
        migrations.AlterModelOptions(
            name='attendancesessionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='biometricrecord',
            options={'ordering': ['-scan_time']},
        ),
        migrations.AlterModelOptions(
            name='classnoticereadstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examresultnotificationreadstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='noticereadstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessionattendance',
            options={'ordering': ['-marked_at']},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'exam_date', 'title')},
        ),
        # notice.target_role is not added here: 0002 already adds this exact
        # field for real, so a second AddField here would fail with
        # "column already exists" on a from-scratch replay.
        migrations.AlterField(
            model_name='attendancesession',
            name='allow_late_minutes',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='qr_refresh_interval',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='biometric_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='biometricrecord',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classnotice',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='classnotice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examattachment',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='reports', to='core.exam'),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='report_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oicassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.school'),
        ),
        migrations.AlterField(
            model_name='oicremark',
            name='remark_type',
            field=models.CharField(choices=[('class', 'Overall Class Performance'), ('subject', 'Subject Performance')], default='class', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('senior_sergeant', 'Senior Sergeant'), ('warrant_officer_ii', 'Warrant Officer II'), ('warrant_officer_i', 'Warrant Officer I'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='BiometricDevice',
        ),
        migrations.DeleteModel(
            name='BiometricUserMapping',
        ),
    ]
