# Generated by Django 5.2.8 on 2025-11-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_classnotice_exam_examreport_attendance_examresult"),
        ("core", "0006_alter_class_capacity"),
    ]

    operations = []
