# Generated by Django 5.2.8 on 2025-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_20251125_2001"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
