# Generated by Django 5.2.8 on 2025-11-26 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_exam_exam_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results_graded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
