# Generated by Django 5.2.8 on 2026-04-25 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_class_code_unique_per_course'),
    ]

    operations = [
        # 0007 was likely fake-applied to work around a RenameField crash, so
        # the biometric tables may still exist in the DB even though migration
        # state thinks they were deleted.  Drop them safely before recreating.
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS biometric_user_mappings CASCADE; "
                "DROP TABLE IF EXISTS biometric_devices CASCADE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. NOC', max_length=200)),
                ('device_type', models.CharField(default='zkteco_f22', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=4370)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('location_description', models.CharField(blank=True, help_text='Physical location of the device', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_sync_records', models.IntegerField(default=0)),
                ('total_synced_records', models.IntegerField(default=0)),
                ('sync_interval_seconds', models.IntegerField(default=30, help_text='HOw often to poll this device (seconds)')),
                ('time_offset_seconds', models.IntegerField(default=0, help_text='Offset to apply if the device clock differs from server')),
                ('connection_timeout', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biometric_devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_user_id', models.CharField(help_text='The user_id stored on the ZKTeco device', max_length=100)),
                ('device_user_name', models.CharField(blank=True, help_text='Name stored on the device (for reference)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'biometric_user_mappings',
            },
        ),
        migrations.RemoveIndex(
            model_name='biometricrecord',
            name='biometric_r_school__330cca_idx',
        ),
        migrations.RemoveIndex(
            model_name='biometricrecord',
            name='biometric_r_biometr_54b67d_idx',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='biometric_id_encrypted',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='biometric_id_hash',
        ),
        migrations.RemoveField(
            model_name='biometricrecord',
            name='raw_data_encrypted',
        ),
        migrations.AlterField(
            model_name='oicassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oic_assignments', to='core.school'),
        ),
        migrations.AlterField(
            model_name='oicremark',
            name='remark_type',
            field=models.CharField(choices=[('class', 'Overall Class Performance'), ('subject', 'Subject Performance')], default='class', max_length=50),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='core.school'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='core.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='mapped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_mappings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_user_mappings', to='core.school'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='biometricdevice',
            unique_together={('school', 'ip_address', 'port')},
        ),
        migrations.AddIndex(
            model_name='biometricusermapping',
            index=models.Index(fields=['device_user_id', 'device'], name='biometric_u_device__ded9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricusermapping',
            index=models.Index(fields=['student', 'device'], name='biometric_u_student_172315_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together={('device', 'device_user_id')},
        ),
    ]
