# Generated by Django 5.2.8 on 2025-12-04 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_examresult_graded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="exams/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.IntegerField(help_text="FIle size in bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.exam",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
