# Generated by Django 5.2.8 on 2025-12-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_examresult_graded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subdomain", models.CharField(max_length=100, unique=True)),
                ("primary_color", models.CharField(default="#004AAD", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("accent_color", models.CharField(default="#000000", max_length=7)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/favicons/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "School admin"),
                    ("instructor", "instructor"),
                    ("student", "student"),
                    ("commandant", "commandant"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.school",
            ),
        ),
    ]
