# Generated by Django 5.2.8 on 2026-05-18 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_biometricdevice_biometricusermapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grading_mode',
            field=models.CharField(choices=[('LEGACY', 'Legacy (Final Exam Only)'), ('POLICY', 'Policy (Component-Based)')], default='LEGACY', help_text='LEGACY = single final exam pass/fail. POLICY = based assessment', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Overall pass mark for this subject', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='eg. "Firing Range Assessment", "CAT 1", "Theory Final"', max_length=150)),
                ('component_type', models.CharField(choices=[('cat', 'Continous Assessment Test'), ('theory', 'Theory Exam'), ('practical', 'Practival Exam'), ('other', 'other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_marks', models.IntegerField(default=100, help_text='Maximum marks for this component', validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Weight of this component in the overall subject score (percentage).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum percentage to pass this component', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_critical', models.BooleanField(default=False, help_text='If True, failing this component means failing the entire subject regardless of overall score. e.g. Firing Range.')),
                ('retake_allowed', models.BooleanField(default=False, help_text='Whether students can retake this component after failing.')),
                ('max_retake_attempts', models.PositiveIntegerField(default=0, help_text='Maximum retake attempts allowed. 0 = unlimited when retake_allowed=True.')),
                ('retake_evaluation', models.CharField(choices=[('latest', 'Use latest Attempt'), ('best', 'Use Best Attempt')], default='latest', help_text='Which attempt score to use: latest or best.', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='core.subject')),
            ],
            options={
                'db_table': 'assessment_components',
                'ordering': ['subject', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentComponentReuslt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt this is (1  = original, 2+ = retakes).')),
                ('is_retake', models.BooleanField(default=False)),
                ('mark_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Computed: (marks_obtained / component.total_marks) * 100', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('RETAKE_REQUIRED', 'Retake Required'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='core.assessmentcomponent')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_results_graded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_component_results', to='core.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='component_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_component_results',
                'ordering': ['component', 'student', '-attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentcomponent',
            index=models.Index(fields=['subject', 'is_active'], name='assessment__subject_34392f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcomponent',
            index=models.Index(fields=['school', 'is_active'], name='assessment__school__471845_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject', 'name'), name='unique_active_component_name_per_subject'),
        ),
        migrations.AddIndex(
            model_name='studentcomponentreuslt',
            index=models.Index(fields=['student', 'component', 'attempt_number'], name='student_com_student_3816d7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcomponentreuslt',
            index=models.Index(fields=['component', 'status'], name='student_com_compone_3c00e1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcomponentreuslt',
            index=models.Index(fields=['school', 'student'], name='student_com_school__b885f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcomponentreuslt',
            constraint=models.UniqueConstraint(fields=('student', 'component', 'attempt_number'), name='unique_attempt_per_student_component'),
        ),
    ]
