# Generated by Django 5.2.8 on 2025-12-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_examattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattachment",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="FIle size in bytes", null=True
            ),
        ),
    ]
