# Generated by Django 5.2.8 on 2026-05-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subject_grading_mode_subject_pass_mark_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentComponentReuslt',
            new_name='StudentComponentResult',
        ),
    ]
