# Generated by Django 5.2.8 on 2025-12-13 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_examattachment_file_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examattachment',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
