# Generated by Django 5.2.8 on 2025-12-08 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_examattachment_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("zkteco", "ZKTECO"), ("fingerprint", "Fingerprint")],
                        default="zkteco",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField(default=4370)),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the device", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("device_password", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "biometric_devices",
                "ordering": ["location", "device_name"],
            },
        ),
        migrations.CreateModel(
            name="BiometricUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biometric_user_id", models.CharField(max_length=100)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "biometric_user_mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "class_obj", "student__last_name"]},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="created_by",
        ),
        migrations.AddField(
            model_name="attendance",
            name="biometric_service_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="biometric_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="marking_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("qr_code", "QR Code"),
                    ("biometric", "Biometric"),
                    ("auto", "Auto"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                default="present",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="classnotice",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="examattachment",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("qr_code", "QR Code"),
                            ("manual", "Manual"),
                            ("biometric", "Biometric"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField()),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("allow_rate_marking", models.BooleanField(default=True)),
                ("late_threshold_minutes", models.IntegerField(default=15)),
                ("auto_mark_absent", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="core.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("marked", "Attendance Marked"),
                            ("updated", "Attendance Updated"),
                            ("deleted", "Attendance Deleted"),
                            ("session_created", "Session Created"),
                            ("session_closed", "Session Closed"),
                            ("biometric_sync", "Biometric Sync"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="core.attendance",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="core.attendancesession",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendance_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="core.attendancesession",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "class_obj", "subject"],
                name="attendance_date_ec8194_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="attendance_student_0943ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["marking_method"], name="attendance_marking_836f5b_idx"
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="default_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_devices",
                to="core.class",
            ),
        ),
        migrations.AddField(
            model_name="biometricusermapping",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_mappings",
                to="core.biometricdevice",
            ),
        ),
        migrations.AddField(
            model_name="biometricusermapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_mappings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["qr_code"], name="attendance__qr_code_7068e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["status", "end_time"], name="attendance__status_50cd4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["class_obj", "subject", "session_date"],
                name="attendance__class_o_e50ae1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["attendance", "timestamp"],
                name="attendance__attenda_6faf54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["action", "timestamp"], name="attendance__action_933ece_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricusermapping",
            index=models.Index(
                fields=["user", "device"], name="biometric_u_user_id_6e5a34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricusermapping",
            index=models.Index(
                fields=["biometric_user_id"], name="biometric_u_biometr_d717da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biometricusermapping",
            unique_together={("device", "biometric_user_id")},
        ),
    ]
