# Generated by Django 5.2.8 on 2026-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_studentcomponentreuslt_studentcomponentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcomponentresult',
            name='mark_obtained',
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='component_type',
            field=models.CharField(choices=[('cat', 'Continuous Assessment Test'), ('theory', 'Theory Exam'), ('practical', 'Practical Exam'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
