# Generated by Django 5.2.8 on 2025-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_examattachment_file_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='examattachment',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
