# Generated by Django 5.2.8 on 2025-12-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_school_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattachment',
            name='school',
        ),
    ]
