# Generated by Django 5.2.8 on 2026-05-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_studentcomponentresult_mark_obtained_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Required for POLICY-graded subjects. Must be an active component belonging to the same subject. NULL for LEGACY-graded subjects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.assessmentcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'component', 'exam_date', 'title')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['component', 'is_active'], name='exams_compone_9cc1f6_idx'),
        ),
    ]
