# Generated by Django 5.2.8 on 2026-01-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_exam_options_alter_examattachment_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('class_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.classnotice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_notice_read_statuses',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'class_notice')},
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notice_read_statuses',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'notice')},
            },
        ),
    ]
