# Generated by Django 5.2.8 on 2026-05-21 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_exam_unique_together_exam_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('instructor_draft', 'Instructor Draft'), ('instructor_submitted', 'Instructor Submitted'), ('oic_draft', 'OIC Draft'), ('oic_submitted', 'OIC Submitted'), ('ci_draft', 'Chief Instructor Draft'), ('ci_submitted', 'Chief Instructor Submitted'), ('commandant_draft', 'Commandant Draft'), ('approved', 'Approved')], db_index=True, default='instructor_draft', max_length=30)),
                ('report_file', models.FileField(blank=True, help_text='Generated PDF after final approval.', null=True, upload_to='course_reports/pdf/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(help_text='Denormalized from enrollment for efficient filtering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reports_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='The specific student enrollment this report is for.', on_delete=django.db.models.deletion.PROTECT, related_name='course_reports', to='core.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='core.school')),
            ],
            options={
                'db_table': 'course_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReportAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Report Created'), ('bulk_created', 'Bulk Reports Created'), ('remark_saved', 'Remark Saved'), ('remark_submitted', 'Remark Submitted'), ('status_changed', 'Status Changed'), ('bulk_submitted', 'Bulk Submitted'), ('approved', 'Report Approved'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: old_status, new_status, stage, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_report_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.coursereport')),
            ],
            options={
                'db_table': 'course_report_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReportStageRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('instructor', 'Instructor'), ('oic', 'OIC'), ('chief_instructor', 'Chief Instructor'), ('commandant', 'Commandant')], db_index=True, max_length=20)),
                ('content', models.TextField(help_text='The remark/assessment text for this student.')),
                ('is_submitted', models.BooleanField(default=False, help_text='Once True, this remark is locked and cannot be edited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_report_remarks', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_remarks', to='core.coursereport')),
            ],
            options={
                'db_table': 'course_report_stage_remarks',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['school', 'is_active'], name='course_repo_school__00c3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['class_obj', 'status'], name='course_repo_class_o_4787e7_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['class_obj', 'is_active'], name='course_repo_class_o_4707ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['enrollment', 'is_active'], name='course_repo_enrollm_d42a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['status', 'is_active'], name='course_repo_status_8b0725_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('enrollment',), name='unique_active_report_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='coursereportauditlog',
            index=models.Index(fields=['report', 'action'], name='course_repo_report__952291_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereportauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='course_repo_perform_ee5541_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereportstageremark',
            constraint=models.UniqueConstraint(fields=('report', 'stage'), name='unique_stage_per_report'),
        ),
    ]
