# Generated by Django 5.2.8 on 2025-12-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_examattachment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattachment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
    ]
