# Generated by Django 5.2.8 on 2026-01-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_classnoticereadstatus_noticereadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnotice',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_notices', to='core.subject'),
        ),
    ]
