# Generated by Django 5.2.8 on 2026-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coursereport_coursereportauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereportauditlog',
            name='report',
        ),
        migrations.RemoveField(
            model_name='coursereportstageremark',
            name='report',
        ),
        migrations.RemoveField(
            model_name='coursereportauditlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='coursereportstageremark',
            name='author',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('cat', 'CAT'), ('final', 'Final'), ('project', 'Project'), ('practical', 'Practical'), ('theory', 'Theory')], default='cat', max_length=20),
        ),
        migrations.DeleteModel(
            name='CourseReport',
        ),
        migrations.DeleteModel(
            name='CourseReportAuditLog',
        ),
        migrations.DeleteModel(
            name='CourseReportStageRemark',
        ),
    ]
