# Generated by Django 5.2.8 on 2026-01-17 03:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_classnotice_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('class', 'Class Session'), ('exam', 'Exam Session'), ('bedcheck', 'Bedcheck Session'), ('lab', 'Lab Session'), ('other', 'Other')], default='class', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_refresh_interval', models.IntegerField(default=30, help_text='Minutes after start time to still mark as present', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
                ('qr_code_secret', models.CharField(blank=True, max_length=255)),
                ('qr_last_generated', models.DateTimeField(blank=True, null=True)),
                ('qr_generation_count', models.IntegerField(default=0)),
                ('enable_qr_scan', models.BooleanField(default=True)),
                ('enable_manual_marking', models.BooleanField(default=True)),
                ('enable_biometric', models.BooleanField(default=False)),
                ('require_location', models.BooleanField(default=False)),
                ('allowed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_radius_meters', models.IntegerField(blank=True, default=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_late_minutes', models.IntegerField(default=10, help_text='Minutes after start time to still mark as present', validators=[django.core.validators.MinValueValidator(0)])),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.subject')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('session_created', 'Session Created'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('session_cancelled', 'Session Cancelled'), ('qr_generated', 'QR Code Generated'), ('attendance_marked', 'Attendance Marked'), ('attendance_updated', 'Attendance Updated'), ('attendance_deleted', 'Attendance Deleted'), ('bulk_import', 'Bulk Import'), ('biometric_sync', 'Biometric Sync')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.attendancesession')),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Session Logs',
                'db_table': 'attendance_session_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10)),
                ('marking_method', models.CharField(choices=[('qr scan', 'QR Code Scan'), ('manual', 'Manual Entry'), ('biometric', 'Biometric'), ('admin', 'Admin Override')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ip_addresses', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked_in_session', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='core.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'db_table': 'session_attendances',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco Device'), ('fingerprint', 'Fingerprint Scanner'), ('other', 'Other')], default='zkteco', max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('biometric_id', models.CharField(help_text='Student ID in biometric device', max_length=100)),
                ('scan_time', models.DateTimeField()),
                ('verification_type', models.CharField(blank=True, max_length=50)),
                ('verification_score', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from device', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to='core.attendancesession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_records', to=settings.AUTH_USER_MODEL)),
                ('session_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_records', to='core.sessionattendance')),
            ],
            options={
                'verbose_name': 'Biometric Record',
                'verbose_name_plural': 'Biometric Records',
                'db_table': 'biometric_records',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_id'], name='attendance__session_14ed26_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_obj', 'scheduled_start'], name='attendance__class_o_b6cb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='attendance__status_498ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['session', 'timestamp'], name='attendance__session_11fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesessionlog',
            index=models.Index(fields=['action', 'timestamp'], name='attendance__action_c2f12b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session', 'status'], name='session_att_session_73faca_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['student', 'marked_at'], name='session_att_student_e77ab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['device_id', 'scan_time'], name='biometric_r_device__432c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['student', 'scan_time'], name='biometric_r_student_35dbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrecord',
            index=models.Index(fields=['processed', 'scan_time'], name='biometric_r_process_44827c_idx'),
        ),
    ]
