# Generated by Django 5.2.8 on 2026-01-10 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_classnotice_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultNotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_statuses', to='core.examresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_notification_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_result_notification_read_statuses',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'exam_result'], name='exam_result_user_id_6d60ea_idx'), models.Index(fields=['read_at'], name='exam_result_read_at_1e64c1_idx')],
                'unique_together': {('user', 'exam_result')},
            },
        ),
    ]
