# Generated by Django 5.2.8 on 2026-01-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_examresult_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
