# Generated by Django 5.2.8 on 2026-01-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendancesession_attendancesessionlog_and_more'),
        ('core', '0016_examresult_graded_at'),
    ]

    operations = [
    ]
