# Generated by Django 5.2.8 on 2026-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_exam_exam_type_alter_user_rank_coursereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('CIII', 'Constable'), ('lance_corporal', 'Lance Corporal'), ('CII', 'CII_Corporal'), ('corporal', 'Corporal'), ('CI', 'CI_Sergeant'), ('sergeant', 'Sergeant'), ('senior_sergeant', 'Senior Sergeant'), ('HCII', 'HCII_Warrant Officer II'), ('warrant_officer_ii', 'Warrant Officer II'), ('HCI', 'HCI_Warrant Officer I'), ('warrant_officer_i', 'Warrant Officer I'), ('2nd_lieutenant', '2nd Lieutenant'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General'), ('civ', 'Civilian')], max_length=20, null=True),
        ),
    ]
