# Generated by Django 5.2.8 on 2026-01-18 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260118_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='qr_refresh_interval',
            field=models.IntegerField(default=300, help_text='Minutes after start time to still mark as present', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.DeleteModel(
            name='ExamResultNotificationReadStatus',
        ),
    ]
