# Generated by Django 5.2.8 on 2026-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereportstageremark',
            name='report',
        ),
        migrations.RemoveField(
            model_name='coursereportauditlog',
            name='report',
        ),
        migrations.RemoveField(
            model_name='coursereportauditlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='coursereportstageremark',
            name='author',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('cat', 'CAT'), ('final', 'Final'), ('project', 'Project'), ('practical', 'Practical'), ('theory', 'Theory')], default='cat', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('lance_corporal', 'Lance Corporal'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('senior_sergeant', 'Senior Sergeant'), ('warrant_officer_ii', 'Warrant Officer II'), ('warrant_officer_i', 'Warrant Officer I'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CourseReport',
        ),
        migrations.DeleteModel(
            name='CourseReportAuditLog',
        ),
        migrations.DeleteModel(
            name='CourseReportStageRemark',
        ),
    ]
