# Generated by Django 5.2.8 on 2026-01-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_attendancesession_qr_refresh_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionattendance',
            old_name='ip_addresses',
            new_name='ip_address',
        ),
    ]
