# Generated by Django 5.2.8 on 2026-01-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_ip_addresses_sessionattendance_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattendance',
            name='marking_method',
            field=models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual Entry'), ('biometric', 'Biometric'), ('admin', 'Admin Override')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to='core.attendancesession'),
        ),
    ]
