# Generated by Django 5.2.8 on 2026-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coursereport_coursereportauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereportstageremark',
            name='character_and_personality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereportstageremark',
            name='command_and_leadership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereportstageremark',
            name='deployment_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereportstageremark',
            name='knowledge_and_ability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereportstageremark',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereportstageremark',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursereportstageremark',
            name='content',
            field=models.TextField(blank=True, help_text='The remark/assessment text for this student (OIC/CI/Commandant stages).', null=True),
        ),
    ]
