# Generated by Django 5.2.8 on 2026-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gradefront_additions'),
        ('core', '0022_fix_missing_component_result_column'),
    ]

    operations = [
    ]
