# Originally generated by Django 5.2.8 on 2026-05-27 13:38
#
# Migration 0022 (fix_missing_component_result_column) applied the following
# to the database directly via raw SQL but with state_operations=[], leaving
# Django's model state behind:
#   - Dropped constraint unique_pending_edit_request_per_result
#   - Added column component_result_id
#   - Created index result_edit_compone_c2dca8_idx
#   - Created unique indexes for per_exam_result and per_component_result
#
# This migration must update Django's model state for those five operations
# without re-running the DDL (which would fail with "already exists").
# SeparateDatabaseAndState is used for those; the remaining operations run
# normally.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_unique_active_membership_per_user'),
    ]

    operations = [
        # ── Already-applied by 0022: update model state only ─────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # DDL already exists; nothing to run.
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='resulteditrequest',
                    name='unique_pending_edit_request_per_result',
                ),
                migrations.AddField(
                    model_name='resulteditrequest',
                    name='component_result',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='edit_requests',
                        to='core.studentcomponentresult',
                    ),
                ),
                migrations.AddIndex(
                    model_name='resulteditrequest',
                    index=models.Index(
                        fields=['component_result', 'status'],
                        name='result_edit_compone_c2dca8_idx',
                    ),
                ),
                migrations.AddConstraint(
                    model_name='resulteditrequest',
                    constraint=models.UniqueConstraint(
                        condition=models.Q(
                            ('exam_result__isnull', False), ('status', 'pending')
                        ),
                        fields=('exam_result',),
                        name='unique_pending_edit_request_per_exam_result',
                    ),
                ),
                migrations.AddConstraint(
                    model_name='resulteditrequest',
                    constraint=models.UniqueConstraint(
                        condition=models.Q(
                            ('component_result__isnull', False), ('status', 'pending')
                        ),
                        fields=('component_result',),
                        name='unique_pending_edit_request_per_component_result',
                    ),
                ),
            ],
        ),

        # ── Normal operations (not yet in DB) ─────────────────────────────────
        migrations.RemoveField(model_name='coursereport', name='class_obj'),
        migrations.RemoveField(model_name='coursereport', name='created_by'),
        migrations.RemoveField(model_name='coursereport', name='enrollment'),
        migrations.RemoveField(model_name='coursereport', name='school'),
        migrations.RemoveField(model_name='coursereportauditlog', name='report'),
        migrations.RemoveField(model_name='coursereportstageremark', name='report'),
        migrations.RemoveField(model_name='coursereportauditlog', name='performed_by'),
        migrations.RemoveField(model_name='coursereportstageremark', name='author'),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(
                choices=[
                    ('cat', 'CAT'), ('final', 'Final'), ('project', 'Project'),
                    ('practical', 'Practical'), ('theory', 'Theory'),
                ],
                default='cat',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(
                blank=True,
                choices=[
                    ('private', 'Private'), ('lance_corporal', 'Lance Corporal'),
                    ('corporal', 'Corporal'), ('sergeant', 'Sergeant'),
                    ('senior_sergeant', 'Senior Sergeant'),
                    ('warrant_officer_ii', 'Warrant Officer II'),
                    ('warrant_officer_i', 'Warrant Officer I'),
                    ('lieutenant', 'Lieutenant'), ('captain', 'Captain'),
                    ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'),
                    ('colonel', 'Colonel'), ('brigadier', 'Brigadier'),
                    ('major_general', 'Major General'),
                    ('lieutenant_general', 'Lieutenant General'), ('general', 'General'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(name='CourseReport'),
        migrations.DeleteModel(name='CourseReportAuditLog'),
        migrations.DeleteModel(name='CourseReportStageRemark'),
    ]
