# Generated by Django 5.2.8 on 2026-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_coursereport_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('lieutenant_general', 'Lieutenant General'), ('major_general', 'Major General'), ('brigadier', 'Brigadier'), ('colonel', 'Colonel'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('major', 'Major'), ('captain', 'Captain'), ('lieutenant', 'Lieutenant'), ('warrant_officer_i', 'Warrant Officer I'), ('warrant_officer_ii', 'Warrant Officer II'), ('senior_sergeant', 'Senior Sergeant'), ('sergeant', 'Sergeant'), ('corporal', 'Corporal'), ('lance_corporal', 'Lance Corporal'), ('private', 'Private'), ('head_constable_i', 'Head Constable I'), ('head_constable_ii', 'Head Constable II'), ('constable_i', 'Constable I'), ('constable_ii', 'Constable II'), ('constable_iii', 'Constable III'), ('civilian', 'Civilian')], max_length=20, null=True),
        ),
    ]
