# Generated by Django 5.2.8 on 2026-07-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_course_report_tables'),
        ('core', '0026_alter_user_rank'),
    ]

    operations = [
    ]
