# Generated by hand on 2026-07-11, reconciling this branch's migration
# graph with the REAL production schema (core/migrations/ was gitignored
# for most of this project's history — see commit c661381 — so production's
# actual applied migration history has no relationship to what's on disk
# here; migrations 0003-0028 were fake-applied to align state before this
# one was written).
#
# Verified against a restored copy of the real production database:
#   - course_reports / course_report_audit_logs / course_report_stage_remarks
#     do not exist yet — course reports were never deployed to production.
#     These need to be created for real.
#   - commandant_school_reports / commandant_report_audit_logs never
#     existed either (that feature was renamed back to CourseReport before
#     ever reaching production) — nothing to actually drop, so those
#     operations are state-only.
#   - users.rank / users.role already match column-for-column; the choices
#     change is metadata-only (no DDL either way).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_chief_of_training_role_and_commandant_report'),
    ]

    operations = [
        # ── Commandant* never existed in production: state-only cleanup ──────
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='commandantschoolreport',
                    name='commandant',
                ),
                migrations.RemoveField(
                    model_name='commandantschoolreport',
                    name='school',
                ),
                migrations.RemoveField(
                    model_name='commandantschoolreport',
                    name='submitted_by',
                ),
                migrations.DeleteModel(
                    name='CommandantReportAuditLog',
                ),
                migrations.DeleteModel(
                    name='CommandantSchoolReport',
                ),
            ],
        ),

        # ── Choices-only metadata changes: no DDL impact ──────────────────────
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('CIII', 'Constable'), ('lance_corporal', 'Lance Corporal'), ('CII', 'CII_Corporal'), ('corporal', 'Corporal'), ('CI', 'CI_Sergeant'), ('sergeant', 'Sergeant'), ('senior_sergeant', 'Senior Sergeant'), ('HCII', 'HCII_Warrant Officer II'), ('warrant_officer_ii', 'Warrant Officer II'), ('HCI', 'HCI_Warrant Officer I'), ('warrant_officer_i', 'Warrant Officer I'), ('2nd_lieutenant', '2nd Lieutenant'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General'), ('civ', 'Civilian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('oic', 'Officer in Charge')], help_text='Base role. Overridden by active membership role when affiliated.', max_length=20),
        ),

        # ── Course reports: genuinely new, never deployed — real DDL ──────────
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('instructor_draft', 'Instructor Draft'), ('instructor_submitted', 'Instructor Submitted'), ('oic_draft', 'OIC Draft'), ('oic_submitted', 'OIC Submitted'), ('ci_draft', 'Chief Instructor Draft'), ('ci_submitted', 'Chief Instructor Submitted'), ('commandant_draft', 'Commandant Draft'), ('approved', 'Approved')], db_index=True, default='instructor_draft', max_length=30)),
                ('report_file', models.FileField(blank=True, help_text='Generated PDF after final approval.', null=True, upload_to='course_reports/pdf/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(help_text='Denormalized from enrollment for efficient filtering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reports_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='The specific student enrollment this report is for.', on_delete=django.db.models.deletion.PROTECT, related_name='course_reports', to='core.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='core.school')),
            ],
            options={
                'db_table': 'course_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReportAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Report Created'), ('bulk_created', 'Bulk Reports Created'), ('remark_saved', 'Remark Saved'), ('remark_submitted', 'Remark Submitted'), ('status_changed', 'Status Changed'), ('bulk_submitted', 'Bulk Submitted'), ('approved', 'Report Approved'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: old_status, new_status, stage, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_report_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.coursereport')),
            ],
            options={
                'db_table': 'course_report_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReportStageRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('instructor', 'Instructor'), ('oic', 'OIC'), ('chief_instructor', 'Chief Instructor'), ('commandant', 'Commandant')], db_index=True, max_length=20)),
                ('content', models.TextField(blank=True, help_text='The remark/assessment text for this student (OIC/CI/Commandant stages).', null=True)),
                ('character_and_personality', models.TextField(blank=True, null=True)),
                ('knowledge_and_ability', models.TextField(blank=True, null=True)),
                ('command_and_leadership', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('deployment_recommendation', models.TextField(blank=True, null=True)),
                ('pad_scores', models.JSONField(blank=True, default=dict, help_text='Personal Ability Dimension scores (1-5), keyed by subject code (instructor stage only). e.g. {"attitude": 3}.')),
                ('is_submitted', models.BooleanField(default=False, help_text='Once True, this remark is locked for the commandant stage. For instructor/oic/chief_instructor stages it can still be corrected until the report is approved (see CORRECTABLE_ROLES).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_report_remarks', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_remarks', to='core.coursereport')),
            ],
            options={
                'db_table': 'course_report_stage_remarks',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['school', 'is_active'], name='course_repo_school__00c3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['class_obj', 'status'], name='course_repo_class_o_4787e7_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['class_obj', 'is_active'], name='course_repo_class_o_4707ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['enrollment', 'is_active'], name='course_repo_enrollm_d42a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereport',
            index=models.Index(fields=['status', 'is_active'], name='course_repo_status_8b0725_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('enrollment',), name='unique_active_report_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='coursereportauditlog',
            index=models.Index(fields=['report', 'action'], name='course_repo_report__952291_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereportauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='course_repo_perform_ee5541_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereportstageremark',
            constraint=models.UniqueConstraint(fields=('report', 'stage'), name='unique_stage_per_report'),
        ),
    ]
