# Generated by Django 5.2.8 on 2026-07-14 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_course_reports_and_reconcile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('issued', 'Certificate Issued'), ('bulk_issued', 'Certificates Bulk Issued'), ('revoked', 'Certificate Revoked'), ('class_closed', 'Class Closed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('template_set_default', 'Template Set Default')], max_length=30)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Request metadata: ip_address, user_agent, counts, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.certificate')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_audit_logs', to='core.class')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_audit_logs', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_audit_subject_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='certificate_school__928cb6_idx'), models.Index(fields=['certificate', 'action'], name='certificate_certifi_bdc01a_idx'), models.Index(fields=['class_obj', 'action'], name='certificate_class_o_901042_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserImportAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('completed', 'Import Completed'), ('failed', 'Import Failed')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='filename, ip_address, total_rows, created_count, failed_count, skipped_count, created_svc_numbers, error_summary, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_import_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_import_audit_logs', to='core.school')),
            ],
            options={
                'db_table': 'user_import_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='user_import_school__6a6de7_idx'), models.Index(fields=['performed_by', 'created_at'], name='user_import_perform_471ba7_idx')],
            },
        ),
    ]
