# Generated by Django 5.2.8 on 2026-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_certificateauditlog_userimportauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='closure_snapshot',
            field=models.JSONField(blank=True, help_text="Identity and stats captured at close_class() time: instructor/subject-instructor ids, student roster, and aggregate counts. Null for classes closed before this field existed, or classes never closed. Used so access checks and summaries for an archived class don't drift if instructor assignments change afterwards.", null=True),
        ),
    ]
