# Generated by Django 5.2.8 on 2026-07-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_totp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_totp_step',
            field=models.BigIntegerField(blank=True, help_text="30s time-step of the last accepted TOTP code, so the same code can't be replayed within its valid_window.", null=True),
        ),
    ]
