# Generated by Django 5.2.8 on 2026-08-05 11:22

import datetime
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_totp_last_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('commandant', 'Commandant'), ('chief_instructor', 'Chief Instructor'), ('oic', 'Officer in Charge'), ('chief_of_training', 'Chief of Training')], help_text='Base role. Overridden by active membership role when affiliated.', max_length=20),
        ),
        migrations.CreateModel(
            name='CommandantSchoolReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('overall_remarks', models.TextField(blank=True)),
                ('statistics_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commandant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_commandant_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandant_reports', to='core.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_commandant_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commandant_school_reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandantReportAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandant_report_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandant_report_audit_logs', to='core.school')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.commandantschoolreport')),
            ],
            options={
                'db_table': 'commandant_report_audit_logs',
                'ordering': ['-timestamp'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='commandantschoolreport',
            index=models.Index(fields=['school', 'status'], name='commandant__school__24c34f_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantschoolreport',
            index=models.Index(fields=['commandant', 'status'], name='commandant__command_b15e67_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantschoolreport',
            index=models.Index(fields=['school', 'report_date'], name='commandant__school__c48a19_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantschoolreport',
            index=models.Index(fields=['status', 'submitted_at'], name='commandant__status_a7e12f_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantreportauditlog',
            index=models.Index(fields=['report', 'timestamp'], name='commandant__report__6a8641_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantreportauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='commandant__action_bd100b_idx'),
        ),
        migrations.AddIndex(
            model_name='commandantreportauditlog',
            index=models.Index(fields=['school', 'timestamp'], name='commandant__school__54bc60_idx'),
        ),
    ]
