# Generated by Django 5.2.8 on 2026-08-17 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_restore_commandant_school_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereport',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student passport photo for this report, supplied by the instructor.', null=True, upload_to='course_reports/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
