# Generated by Django 5.2.8 on 2026-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_coursereport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereportauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Report Created'), ('bulk_created', 'Bulk Reports Created'), ('remark_saved', 'Remark Saved'), ('remark_submitted', 'Remark Submitted'), ('status_changed', 'Status Changed'), ('bulk_submitted', 'Bulk Submitted'), ('approved', 'Report Approved'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('photo_uploaded', 'Student Photo Uploaded'), ('photo_removed', 'Student Photo Removed')], max_length=30),
        ),
    ]
