# Generated by Django 5.2.8 on 2026-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_certificate_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandantreportauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('pdf_downloaded', 'PDF Downloaded')], max_length=20),
        ),
    ]
