# Generated by Django 5.2.8 on 2026-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_commandantreportauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_emailed_at',
            field=models.DateTimeField(blank=True, help_text='Set atomically by the delivery task to claim the send and prevent duplicates.', null=True),
        ),
        migrations.AlterField(
            model_name='certificateauditlog',
            name='action',
            field=models.CharField(choices=[('issued', 'Certificate Issued'), ('bulk_issued', 'Certificates Bulk Issued'), ('revoked', 'Certificate Revoked'), ('class_closed', 'Class Closed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('template_set_default', 'Template Set Default'), ('email_sent', 'Certificate Emailed'), ('email_failed', 'Certificate Email Failed')], max_length=30),
        ),
    ]
