# Generated by Django 5.2.8 on 2026-08-25 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0037_certificate_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('other', 'Other'), ('delete_user', 'User Deleted'), ('delete_exam', 'Exam Deleted'), ('delete_course', 'Course Deleted'), ('delete_certificate', 'Certificate Deleted'), ('role_changed', 'Role Changed'), ('user_deactivated', 'User Deactivated'), ('login', 'Login'), ('logout', 'Logout')], max_length=40)),
                ('actor_identifier', models.CharField(blank=True, help_text="svc_number/username snapshot, or 'system' — survives actor deletion.", max_length=150)),
                ('actor_display_name', models.CharField(blank=True, max_length=300)),
                ('actor_role', models.CharField(blank=True, help_text="Role label at the time of the event, not the actor's current role.", max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=150)),
                ('target_object_id', models.CharField(blank=True, help_text='str(pk) — CharField because target PKs vary (int, UUID, ...).', max_length=64)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable snapshot of the target, captured before deletion where relevant.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=36)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('success', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='core.school')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['school', 'created_at'], name='audit_school_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='audit_target_idx'), models.Index(fields=['request_id'], name='audit_request_id_idx')],
            },
        ),
    ]
