# Generated by Django 5.2.8 on 2026-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_membership_transferred_audit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('other', 'Other'), ('delete_user', 'User Deleted'), ('delete_exam', 'Exam Deleted'), ('delete_course', 'Course Deleted'), ('delete_class', 'Class Deleted'), ('delete_certificate', 'Certificate Deleted'), ('delete_course_report', 'Course Report Deleted'), ('create_user', 'User Created'), ('role_changed', 'Role Changed'), ('user_deactivated', 'User Deactivated'), ('user_activated', 'User Activated'), ('privilege_changed', 'Privilege Changed'), ('membership_role_changed', 'School Membership Role Changed'), ('membership_transferred', 'School Membership Transferred'), ('department_role_changed', 'Department Membership Role Changed'), ('oic_assigned', 'OIC Assigned'), ('oic_unassigned', 'OIC Unassigned'), ('marks_changed', 'Marks Changed'), ('bulk_marks_changed', 'Marks Changed (Bulk)'), ('result_edit_approved', 'Result Edit Request Approved'), ('result_edit_rejected', 'Result Edit Request Rejected'), ('export', 'Data Exported'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout')], max_length=40),
        ),
    ]
