const RANK_ABBR = {
  'General': 'Gen',
  'Lieutenant General': 'Lt Gen',
  'Major General': 'Maj Gen',
  'Brigadier': 'Brig',
  'Colonel': 'Col',
  'Lieutenant Colonel': 'Lt Col',
  'Major': 'Maj',
  'Captain': 'Capt',
  'Lieutenant': 'Lt',
  'Warrant Officer I': 'WO1',
  'Warrant Officer Ii': 'Woii',
  'Warrant Officer II': 'Woii',
  'Senior Sergeant': 'SSgt',
  'Sergeant': 'Sgt',
  'Corporal': 'Cpl',
  'Lance Corporal': 'LCpl',
  'Private': 'Spte',
  'Head Constable I': 'HC1',
  'Head Constable Ii': 'HC2',
  'Head Constable II': 'HC2',
  'Constable I': 'Cst1',
  'Constable Ii': 'Cst2',
  'Constable II': 'Cst2',
  'Constable Iii': 'Cst3',
  'Constable III': 'Cst3',
  'Civilian': 'Civ',
  // Raw API values
  'general': 'Gen',
  'lieutenant_general': 'Lt Gen',
  'major_general': 'Maj Gen',
  'brigadier': 'Brig',
  'colonel': 'Col',
  'lieutenant_colonel': 'Lt Col',
  'major': 'Maj',
  'captain': 'Capt',
  'lieutenant': 'Lt',
  'warrant_officer_i': 'WO1',
  'warrant_officer_ii': 'Woii',
  'senior_sergeant': 'SSgt',
  'sergeant': 'Sgt',
  'corporal': 'Cpl',
  'lance_corporal': 'LCpl',
  'private': 'Spte',
  'head_constable_i': 'HC1',
  'head_constable_ii': 'HC2',
  'constable_i': 'Cst1',
  'constable_ii': 'Cst2',
  'constable_iii': 'Cst3',
  'civilian': 'Civ',
}

export function shortRank(rank) {
  if (!rank) return ''
  return RANK_ABBR[rank] || RANK_ABBR[rank.trim()] || rank
}
